-- Nutrac database

DROP DATABASE IF EXISTS <NUTRAC_DB>;

CREATE DATABASE <NUTRAC_DB> WITH
    OWNER = <NUTRAC_USER>
    TEMPLATE = template0
    ENCODING = 'UTF-8';

GRANT ALL ON DATABASE <NUTRAC_DB> TO <NUTRAC_USER>;

ALTER SCHEMA public OWNER TO <NUTRAC_USER>;
